name: MINGW
on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'Test/**'
      - '**/*.md'
      - '**/*.txt'
      - '**/*.sys'
      - '**/*.dll'
      - '**/*.exe'
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Setup MinGW Build Environment
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
        version: '12.2.0'
    - name: Verify MinGW Build Environment
      shell: cmd
      run: |
        ECHO.
        g++ --version
    - name: Perform Building
      working-directory: ${{env.GITHUB_WORKSPACE}}
      shell: cmd
      run: |
        CD tools
        SET VU_CI_BUILD=1
        MinGW.Build.Static.Library.CMD
